### ISSUE TITLE
Save userId in cookie

### ISSUE THREAD

**Issue by feralheart** [botman/web-widget#10]
Right now if we don't add an `userId`, the JS generates one randomly when he/she opens the window.
This means when the user refreshes the page, or navigates to an another he/she gets a new one.
In a future update it would be wise if we could save in a cookie.

**Comment by sschlein** [comment]
Hi, that's on purpose. The widget is build for extending and in many use cases it makes sense to handle the user id within the application and don't generate one on the client side.
