### ISSUE TITLE
Npm run dev failing

### ISSUE THREAD

**Issue by sketchminds** [botman/web-widget#14]
Hi,

I got the following issues when I execute the npm run dev:

ERROR in [at-loader] ./src/chat/messages/messagetype.tsx:22:24
    TS2540: Cannot assign to 'visible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/messagetype.tsx:23:24
    TS2540: Cannot assign to 'visibilityChanged' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/action.tsx:29:24
    TS2540: Cannot assign to 'attachmentsVisible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/buttons.tsx:31:24
    TS2540: Cannot assign to 'attachmentsVisible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/typing-indicator.tsx:16:24
    TS2540: Cannot assign to 'visible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/chat.tsx:19:20
    TS2540: Cannot assign to 'messages' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/chat.tsx:20:20
    TS2540: Cannot assign to 'replyType' because it is a constant or a read-only property.
Webpack: Failed to compile

**Comment by mohsinht** [comment]
I'm getting:
```
10% building modules 2/2 modules 0 activeevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at GetAddrInfoReqWrap.doListen (net.js:1481:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botman-web-widget@0.0.20 dev: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botman-web-widget@0.0.20 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohsin Hayat\AppData\Roaming\npm-cache\_logs\2018-08-13T07_24_37_341Z-debug.log
```

**Comment by mohsinht** [comment]
Now I'm getting this error when I run `npm run build` :

```
ERROR in [at-loader] ./src/chat/messages/messagetype.tsx:22:24
    TS2540: Cannot assign to 'visible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/messagetype.tsx:23:24
    TS2540: Cannot assign to 'visibilityChanged' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/action.tsx:29:24
    TS2540: Cannot assign to 'attachmentsVisible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/buttons.tsx:31:24
    TS2540: Cannot assign to 'attachmentsVisible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/messages/typing-indicator.tsx:16:24
    TS2540: Cannot assign to 'visible' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/chat.tsx:19:20
    TS2540: Cannot assign to 'messages' because it is a constant or a read-only property.

ERROR in [at-loader] ./src/chat/chat.tsx:20:20
    TS2540: Cannot assign to 'replyType' because it is a constant or a read-only property.
```

**Comment by joaquin03** [comment]
Same problem here. The PR fix the problem! Thanks!

**Comment by danlopez00** [comment]
you have to change all the `this.state.` to `this.setState({});` for example:

on action.tsx:

`this.setState({ attachmentsVisible : false});`

**Comment by danlopez00** [comment]
This should be resolved. Try the develop branch
