### ISSUE TITLE
really wish this was rewritten in Vue!!

### ISSUE THREAD

**Issue by vesper8** [botman/web-widget#26]
I mean.. like everything Laravel.. it's a bummer this is written in React.. makes it hard to pull in and blend in with my vue front-end 

has anyone got a vue fork perchance? ; )

**Comment by Edd-G** [comment]
Hello!
You may use this vue-chat: https://github.com/mattmezza/vue-beautiful-chat
Or use botman/vue-tinker-component as prototype: https://github.com/botman/vue-tinker-component

**Comment by vesper8** [comment]
thanks for the suggestions @Edd-G !

The botman tinker component is extremely bare and doesn't have any of the features of the web-widget.. however the vue-beautiful-chat looks great and it looks perfect to replace the web widget so thanks for sharing that

**Comment by danlopez00** [comment]
Please take a look at the tinker lib. This actually needs a lot of work to make it production ready.
