### ISSUE TITLE
Urgent Issue - Conversation not working in web-widget

### ISSUE THREAD

**Issue by sumoydas** [botman/web-widget#27]
Hi Marcel,

Today first time I have used Botman application. I have created a web-widget by using simple php file (without using any framework and without BotMan Studio). Initially I have implemented a basic example and it worked fine.

Then I try to implement the conversation logic by using the same files but its not working. when user submit a reply bot unable to read it and display it on the next phase.

In my project root there are only one folder "vendor" and 5 files composer.json. composer.lock, index.php, chat.php and chat.html

I'm using the PHP version: 7.1.11

Here I'm attaching my project folder
![botman-issue](https://user-images.githubusercontent.com/50166064/57012372-c669fa00-6c23-11e9-93e3-5b93569768fc.png)
[botman.zip](https://github.com/botman/web-widget/files/3134180/botman.zip)

 so you can check the issue and suggest me the actual solution for it.

**Comment by sumoydas** [comment]
Hello Marcel,

As per https://github.com/botman/botman/issues/778 this link I modified my **composer.json** file and added **Doctrine Cache code** in my chat.php 

Now, when user submit his/her first text **"hello"** no reply has been displayed in the chatbot but the **following error is shown in the console**:

<b>Warning</b>:  var_export does not handle circular references in <b>E:\xampp\htdocs\botman\vendor\doctrine\cache\lib\Doctrine\Common\Cache\PhpFileCache.php</b> on line <b>96</b><br />
{"status":200,"messages":[{"type":"text","text":"Hello! What is your firstname?","attachment":null,"additionalParameters":[]}]}

And if I'm **submitting any text again** then chatbot does not show anything but generates the **following error in console**:

<b>Fatal error</b>:  Uncaught Error: Call to undefined method BotMan\BotMan\BotMan::__set_state() in E:\xampp\htdocs\botman\cache\1c\5b636f6e766572736174696f6e2d353966353132663464333136393666346630313032376261376438303834363933353464363663352d353966353132663464333136393666346630313032376261376438303834363933353464363663355d5b315d.doctrinecache.php:9
Stack trace:
#0 E:\xampp\htdocs\botman\vendor\doctrine\cache\lib\Doctrine\Common\Cache\PhpFileCache.php(112): include()
#1 E:\xampp\htdocs\botman\vendor\doctrine\cache\lib\Doctrine\Common\Cache\PhpFileCache.php(63): Doctrine\Common\Cache\PhpFileCache-&gt;includeFileForId('[conversation-5...')
#2 E:\xampp\htdocs\botman\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php(124): Doctrine\Common\Cache\PhpFileCache-&gt;doContains('[conversation-5...')
#3 E:\xampp\htdocs\botman\vendor\botman\botman\src\Cache\DoctrineCache.php(31): Doctrine\Common\Cache\CacheProvider-&gt;contains('conversation-59...')
#4 E:\xampp\htdocs\botman\vendor\botman\botman\src\Traits\HandlesConversations.php(173) in <b>E:\xampp\htdocs\botman\cache\1c\5b636f6e766572736174696f6e2d353966353132663464333136393666346630313032376261376438303834363933353464363663352d353966353132663464333136393666346630313032376261376438303834363933353464363663355d5b315d.doctrinecache.php</b> on line <b>9</b><br />

Here I have attached my project code zip and the screenshot of the chatbot.
[botman.zip](https://github.com/botman/web-widget/files/3134552/botman.zip)
![botman-issue1](https://user-images.githubusercontent.com/50166064/57017873-b3b0ee80-6c3e-11e9-93b5-14d4c535416a.png)

Please find the attachments and tell me how can i solve this issues.

Thank You

**Comment by mostar** [comment]
Hi,
Probably the php execution fail.
Check you web server log  fro the error message.
