### ISSUE TITLE
Custom CSS replaced with JsDelivr ?

### ISSUE THREAD

**Issue by phileastv** [botman/web-widget#44]
Hello!

I'm currently trying to customize the look of the web widget. I achieved to do my modifications, both in some .tsx files and in the chat.css located in src/assets/CSS. The widget and the demo.html/chat.html shows all my modifications on the CSS file when I'm running the dev script.

But when I build my widget to create one single file I include on my website, all the changes made in "chat.css" are gone. It seems like the build processes replace the CSS by a minified version from JsDelivr's CDN, which obviously, does not have my changes.

![image](https://user-images.githubusercontent.com/20335741/66768290-8ab1ac80-eeb2-11e9-8a8b-2f91ed3277c1.png)

I tried to search in all the files and node modules to see if it was a script who changed the link to the CSS files, but I didn't find anything.

Would you have any idea to how to persist those changes and keep my original CSS file?

Thank you so much for all your hard work on Botman and it's very helpful documentation. I'm using it to create an adventure game and was such a perfect tool for this.

**Comment by phileastv** [comment]
Just found what I was doing wrong.

The main widget.js _(that you integrate in your webpage)_, seems to call the other necessaries files _(for example chat.js and chat.css)_ from the /storage/framework/views folder of your Botman's project.

In this folder, you have multiples .php files with hash names, which tells the widget the path to get chat.min.css and chat.js (and which are by default JsDelivr external CDN). So you can just change this to your local path instead.

You can also change the path of where those compiled files are in the config/view.php folder.

In the end, this was fairly simple, but the answer was not clear for me at first. Hope this will help other !

Close#44

**Comment by Zeeshan-H** [comment]
No i still can't find the solution. Please help me with that. I just want to change the style of the button inside the chat.css file. Please help.
