### ISSUE TITLE
How do you remove the background svg

### ISSUE THREAD

**Issue by roarkmccolgan** [botman/web-widget#54]
Hi!
Is there a way to remove the background svg in the chat window using the api?

![image](https://user-images.githubusercontent.com/1567162/85282986-e80feb80-b48c-11ea-9ff7-1af3feaa751e.png)

Thanks!

**Comment by roarkmccolgan** [comment]
I just overrode the the css, thanks

**Comment by Zeeshan-H** [comment]
How to override the chat.css file?

**Comment by Ochegbinu** [comment]
> How to override the chat.css file?

Just comment it out

**Comment by 4nd114** [comment]
$(document).on('click', '.desktop-closed-message-avatar img', function() {
    var iframe = document.getElementById("chatBotManFrame");
    iframe.addEventListener('load', function () {
        var htmlFrame = this.contentWindow.document.getElementsByTagName("html")[0];
        var bodyFrame = this.contentWindow.document.getElementsByTagName("body")[0];
        var headFrame = this.contentWindow.document.getElementsByTagName("head")[0];

        var image = "https://images.unsplash.com/photo-1501597301489-8b75b675ba0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1349&q=80"

        htmlFrame.style.backgroundImage = "url("+image+")";
        bodyFrame.style.backgroundImage = "url("+image+")";
    });
});

**Comment by 4nd114** [comment]
```
$(document).on('click', '.desktop-closed-message-avatar img', function() {
    var iframe = document.getElementById("chatBotManFrame");
    iframe.addEventListener('load', function () {
        var htmlFrame = this.contentWindow.document.getElementsByTagName("html")[0];
        var bodyFrame = this.contentWindow.document.getElementsByTagName("body")[0];
        var headFrame = this.contentWindow.document.getElementsByTagName("head")[0];

        var image = "https://images.unsplash.com/photo-1501597301489-8b75b675ba0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1349&q=80"

        htmlFrame.style.backgroundImage = "url("+image+")";
        bodyFrame.style.backgroundImage = "url("+image+")";
    });
});
```

**Comment by 4nd114** [comment]
For mobile update .desktop-closed-message-avatar img to .mobile-closed-message-avatar img
