### ISSUE TITLE
Laravel Echo

### ISSUE THREAD

**Issue by dejury** [botman/web-widget#55]
Hi guys,

I see some references to laravel-echo in the code, but I can't figure out how to make this work.
Is there a driver which needs to be installed on botman?

And when I try to do useEcho: true, i get the error Pusher is not defined. Of course i included this inside package.json. I can't find any documentation of this part (yet).

Thanks in advance,

**Comment by filippotoso** [comment]
You need to installa and configure a websocket server.

https://laravel.com/docs/9.x/broadcasting
https://beyondco.de/docs/laravel-websockets/getting-started/introduction
