### ISSUE TITLE
Customize web widget

### ISSUE THREAD

**Issue by sketchminds** [botman/web-widget#9]
Hi Marcel,

Thanks for this great library. I'm still exploring the botman but I have question in using the web widget. For example I want to customize the web widget, how can I do that and apply to my current botman studio project setup?

I just want to try out for myself to create custom templates and custom UI and UX on web widget, for example adding Get Started button and action on the very start of the chat, etc.

Thanks.

**Comment by mpociot** [comment]
Hi,

Yes, you can customize the web widget. To get started with it, clone the web-widget repository and do a `npm install`.
Once you have all the dependencies for the web widget, you can try it locally by running `npm run dev`. This will start a dev-server and launch your web browser with the `demo.html`. To change your widget configuration, simply edit the demo.html file to point to your local BotMan Studio installation.
Then you can just modify the code / style of the web widget and try it out.

**Comment by sketchminds** [comment]
Hi,

Thank you! I'll try this out.

**Comment by grillol** [comment]
Hi Marcel, thanks for the job you have done. 

I would like to improve the web widget action.

For example, I would like the user to fill in a list of values before sending the message (ex: work experience list), or to have an autocomplete option, etc.

Would it be possible to have minimal documentation of the code and some suggestions to contribute on this direction? 

Thanks a lot.

**Comment by speedygonzales77** [comment]
Thanks. This is a great article.
